CREATE TABLE phot (
  id INTEGER PRIMARY KEY,
  starname TEXT,
  cad int,
  t real,
  fmask int,
  f_unweighted real,
  f_weighted real,
  f_weighted2 real,
  f_weighted3 real,
  f_weighted4 real,
  f_weighted5 real,
  f_weighted6 real,
  f_weighted7 real,
  dx real,
  dy real, 
  m01 real,
  m10 real,
  mupr02 real,
  mupr11 real,
  mupr20 real
);
