CREATE TABLE headers (
  id INTEGER PRIMARY KEY,
  fitsfile TEXT NULL,
  KEPLERID INT NULL,
  OBJECT TEXT NULL,
  CHANNEL INT NULL,
  MODULE INT  NULL,
  OUTPUT INT NULL,
  CAMPAIGN INT NULL,
  NAXIS INT NULL,
  NAXIS1 INT NULL,
  NAXIS2 INT NULL,
  TDIM4 TEXT NULL,
  REF_ROW INT NULL,
  REF_COL INT NULL
);
